<a href="https://colab.research.google.com/github/bitnahian/ThinkStats-Purpleshoes/blob/master/chap01ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#setup thinkstats on colabs.

!git clone https://github.com/AllenDowney/ThinkStats2
!cp -r /content/ThinkStats2/code/* .

Cloning into 'ThinkStats2'...
remote: Enumerating objects: 2628, done.
remote: Total 2628 (delta 0), reused 0 (delta 0), pack-reused 2628
Receiving objects: 100% (2628/2628), 171.99 MiB | 36.88 MiB/s, done.
Resolving deltas: 100% (1480/1480), done.
Checking out files: 100% (482/482), done.


# Examples and Exercises from Think Stats, 2nd Edition

http://thinkstats2.com

Copyright 2016 Allen B. Downey

MIT License: https://opensource.org/licenses/MIT


In [0]:
from __future__ import print_function, division

import nsfg

## Examples from Chapter 1

Read NSFG data into a Pandas DataFrame.

In [3]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  ...  secu_p  sest  cmintvw  totalwgt_lb
0       1         1        NaN        NaN  ...       2     9      NaN       8.8125
1       1         2        NaN        NaN  ...       2     9      NaN       7.8750
2       2         1        NaN        NaN  ...       2    12      NaN       9.1250
3       2         2        NaN        NaN  ...       2    12      NaN       7.0000
4       2         3        NaN        NaN  ...       2    12      NaN       6.1875

[5 rows x 244 columns]

Print the column names.

In [4]:
preg.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

Select a single column name.

In [5]:
preg.columns[1]

'pregordr'

Select a column and check what type it is.

In [6]:
pregordr = preg['pregordr']
type(pregordr)

pandas.core.series.Series

Print a column.

In [7]:
pregordr

0        1
1        2
2        1
3        2
4        3
5        1
6        2
7        3
8        1
9        2
10       1
11       1
12       2
13       3
14       1
15       2
16       3
17       1
18       2
19       1
20       2
21       1
22       2
23       1
24       2
25       3
26       1
27       1
28       2
29       3
        ..
13563    2
13564    3
13565    1
13566    1
13567    1
13568    2
13569    1
13570    2
13571    3
13572    4
13573    1
13574    2
13575    1
13576    1
13577    2
13578    1
13579    2
13580    1
13581    2
13582    3
13583    1
13584    2
13585    1
13586    2
13587    3
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, Length: 13593, dtype: int64

Select a single element from a column.

In [9]:
pregordr[0]

1

Select a slice from a column.

In [10]:
pregordr[2:5]

2    1
3    2
4    3
Name: pregordr, dtype: int64

Select a column using dot notation.

In [0]:
pregordr = preg.pregordr

Count the number of times each value occurs.

In [12]:
preg.outcome.value_counts().sort_index()

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

Check the values of another variable.

In [13]:
preg.birthwgt_lb.value_counts().sort_index()

0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

Make a dictionary that maps from each respondent's `caseid` to a list of indices into the pregnancy `DataFrame`.  Use it to select the pregnancy outcomes for a single respondent.

In [14]:
caseid = 10229
preg_map = nsfg.MakePregMap(preg)
indices = preg_map[caseid]
preg.outcome[indices].values

array([4, 4, 4, 4, 4, 4, 1])

## Exercises

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611933)

In [20]:
# Solution goes here
preg.birthord.value_counts().sort_index()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [21]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)

In [24]:
# Solution goes here
preg.prglngth.value_counts().sort_index()

0       15
1        9
2       78
3      151
4      412
5      181
6      543
7      175
8      409
9      594
10     137
11     202
12     170
13     446
14      29
15      39
16      44
17     253
18      17
19      34
20      18
21      37
22     147
23      12
24      31
25      15
26     117
27       8
28      38
29      23
30     198
31      29
32     122
33      50
34      60
35     357
36     329
37     457
38     609
39    4744
40    1120
41     591
42     328
43     148
44      46
45      10
46       1
47       1
48       7
50       2
Name: prglngth, dtype: int64

To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [25]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [27]:
preg['totalwgt_kg'] = preg['totalwgt_lb']/2.205
print(preg.totalwgt_kg)

0        3.996599
1        3.571429
2        4.138322
3        3.174603
4        2.806122
5        3.883220
6        4.336735
7        3.798186
8        3.429705
9        3.004535
10       3.543084
11       3.174603
12       1.814059
13            NaN
14            NaN
15       3.486395
16       3.401361
17       2.862812
18            NaN
19       3.968254
20       3.713152
21       2.522676
22            NaN
23       3.061224
24       3.344671
25       3.089569
26       3.684807
27       3.231293
28       2.749433
29       3.373016
           ...   
13563    3.486395
13564    3.458050
13565    3.684807
13566    3.401361
13567         NaN
13568         NaN
13569    2.636054
13570    3.032880
13571    2.721088
13572    2.636054
13573    2.976190
13574    2.777778
13575         NaN
13576    2.919501
13577         NaN
13578    2.721088
13579    3.174603
13580         NaN
13581    2.891156
13582         NaN
13583         NaN
13584    2.891156
13585         NaN
13586         NaN
13587     

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [0]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [29]:
resp.head()

caseid  rscrinf  rdormres  ...  cmlstyr  screentime   intvlngth
0    2298        1         5  ...     1222    18:26:36  110.492667
1    5012        1         5  ...     1221    16:30:59   64.294000
2   11586        1         5  ...     1222    18:19:09   75.149167
3    6794        5         5  ...     1222    15:54:43   28.642833
4     616        1         5  ...     1221    14:19:44   69.502667

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [30]:
# Solution goes here
resp.age_r.value_counts().sort_index()

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [31]:
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  ...  cmlstyr  screentime   intvlngth
0    2298        1         5  ...     1222    18:26:36  110.492667

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [32]:
preg[preg.caseid==2298]

caseid  pregordr  howpreg_n  ...  cmintvw  totalwgt_lb  totalwgt_kg
2610    2298         1        NaN  ...      NaN       6.8750     3.117914
2611    2298         2        NaN  ...      NaN       5.5000     2.494331
2612    2298         3        NaN  ...      NaN       4.1875     1.899093
2613    2298         4        NaN  ...      NaN       6.8750     3.117914

[4 rows x 245 columns]

How old is the respondent with `caseid` 1?

In [43]:
# Solution goes here
resp[resp.caseid==1].age_r

1069    44
Name: age_r, dtype: int64

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [53]:
# Solution goes here
preg[preg.caseid==2298].prglngth

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [56]:
# Solution goes here
preg[preg.caseid==5012].birthwgt_lb

5515    6.0
Name: birthwgt_lb, dtype: float64